apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ss78zaku5-java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ss78zaku5-java-springboot 
  name: ss78zaku5-java-springboot
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ss78zaku5-java-springboot
    weight: 100 
